# -*- coding: utf-8 -*-
"""PalmerPenguinsM2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eLbjqSnGic5_FTXT70ox3xfodwDGVdRV
"""

# PalmerPenguinsM2.py
# Joseph Kurtz
# 10/2/2026
# Introduces the Palmer Penguin species

# constants representing the species and count
SP_CHINSTRAP = 68
SP_GENTOO = 123
SP_ADELIE = 151
TOTAL_SPECIES = 3

import math

total_penguins = SP_CHINSTRAP + SP_GENTOO + SP_ADELIE
average_penguins = total_penguins / TOTAL_SPECIES
average_penguins_rounded_up = math.ceil(average_penguins)

chinstrap_percentage = SP_CHINSTRAP / total_penguins * 100
gentoo_percentage = SP_GENTOO / total_penguins * 100
adelie_percentage = SP_ADELIE / total_penguins * 100




# output the species names with introductory text
print("Introducing the Palmer Penguins:\n")

print("\tChinstrap!")
print("\tGentoo!")
print("and last but not least...")
print("\tAdelie!")
print()
print("There are a total of " +
str(TOTAL_SPECIES) +
" penguin species in this dataset.")
print("There are a total of " +
str(total_penguins) +
" penguins in the dataset.")
print("The average number of penguins per species is " +
str(average_penguins))
print("The average rounded up is " +
str(average_penguins_rounded_up) +
" penguins.")

print("Chinstrap:", SP_CHINSTRAP, chinstrap_percentage)
print("Gentoo:", SP_GENTOO, gentoo_percentage)
print("Adelie:", SP_ADELIE, adelie_percentage)